spring.application.name=D01-Spring-boot-Security
spring.security.user.name = nivrutti
spring.security.user.password = Nivrutti@9307
spring.security.user.name = nivrutti
spring.security.user.password = Nivrutti@9307
